// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portUpdates.proto

package port_ops.serialized_update;

public final class PortUpdatesProto {
  private PortUpdatesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PortUpdatesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .SinglePortUpdate updates = 1;
    /**
     * <code>repeated .SinglePortUpdate updates = 1;</code>
     */
    java.util.List<port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate> 
        getUpdatesList();
    /**
     * <code>repeated .SinglePortUpdate updates = 1;</code>
     */
    port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate getUpdates(int index);
    /**
     * <code>repeated .SinglePortUpdate updates = 1;</code>
     */
    int getUpdatesCount();
    /**
     * <code>repeated .SinglePortUpdate updates = 1;</code>
     */
    java.util.List<? extends port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdateOrBuilder> 
        getUpdatesOrBuilderList();
    /**
     * <code>repeated .SinglePortUpdate updates = 1;</code>
     */
    port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdateOrBuilder getUpdatesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PortUpdates}
   */
  public static final class PortUpdates extends
      com.google.protobuf.GeneratedMessage
      implements PortUpdatesOrBuilder {
    // Use PortUpdates.newBuilder() to construct.
    private PortUpdates(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PortUpdates(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PortUpdates defaultInstance;
    public static PortUpdates getDefaultInstance() {
      return defaultInstance;
    }

    public PortUpdates getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PortUpdates(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                updates_ = new java.util.ArrayList<port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate>();
                mutable_bitField0_ |= 0x00000001;
              }
              updates_.add(input.readMessage(port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          updates_ = java.util.Collections.unmodifiableList(updates_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return port_ops.serialized_update.PortUpdatesProto.internal_static_PortUpdates_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return port_ops.serialized_update.PortUpdatesProto.internal_static_PortUpdates_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              port_ops.serialized_update.PortUpdatesProto.PortUpdates.class, port_ops.serialized_update.PortUpdatesProto.PortUpdates.Builder.class);
    }

    public static com.google.protobuf.Parser<PortUpdates> PARSER =
        new com.google.protobuf.AbstractParser<PortUpdates>() {
      public PortUpdates parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PortUpdates(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PortUpdates> getParserForType() {
      return PARSER;
    }

    // repeated .SinglePortUpdate updates = 1;
    public static final int UPDATES_FIELD_NUMBER = 1;
    private java.util.List<port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate> updates_;
    /**
     * <code>repeated .SinglePortUpdate updates = 1;</code>
     */
    public java.util.List<port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate> getUpdatesList() {
      return updates_;
    }
    /**
     * <code>repeated .SinglePortUpdate updates = 1;</code>
     */
    public java.util.List<? extends port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdateOrBuilder> 
        getUpdatesOrBuilderList() {
      return updates_;
    }
    /**
     * <code>repeated .SinglePortUpdate updates = 1;</code>
     */
    public int getUpdatesCount() {
      return updates_.size();
    }
    /**
     * <code>repeated .SinglePortUpdate updates = 1;</code>
     */
    public port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate getUpdates(int index) {
      return updates_.get(index);
    }
    /**
     * <code>repeated .SinglePortUpdate updates = 1;</code>
     */
    public port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdateOrBuilder getUpdatesOrBuilder(
        int index) {
      return updates_.get(index);
    }

    private void initFields() {
      updates_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getUpdatesCount(); i++) {
        if (!getUpdates(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < updates_.size(); i++) {
        output.writeMessage(1, updates_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < updates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, updates_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static port_ops.serialized_update.PortUpdatesProto.PortUpdates parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static port_ops.serialized_update.PortUpdatesProto.PortUpdates parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static port_ops.serialized_update.PortUpdatesProto.PortUpdates parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static port_ops.serialized_update.PortUpdatesProto.PortUpdates parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static port_ops.serialized_update.PortUpdatesProto.PortUpdates parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static port_ops.serialized_update.PortUpdatesProto.PortUpdates parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static port_ops.serialized_update.PortUpdatesProto.PortUpdates parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static port_ops.serialized_update.PortUpdatesProto.PortUpdates parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static port_ops.serialized_update.PortUpdatesProto.PortUpdates parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static port_ops.serialized_update.PortUpdatesProto.PortUpdates parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(port_ops.serialized_update.PortUpdatesProto.PortUpdates prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PortUpdates}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements port_ops.serialized_update.PortUpdatesProto.PortUpdatesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return port_ops.serialized_update.PortUpdatesProto.internal_static_PortUpdates_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return port_ops.serialized_update.PortUpdatesProto.internal_static_PortUpdates_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                port_ops.serialized_update.PortUpdatesProto.PortUpdates.class, port_ops.serialized_update.PortUpdatesProto.PortUpdates.Builder.class);
      }

      // Construct using port_ops.serialized_update.PortUpdatesProto.PortUpdates.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUpdatesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (updatesBuilder_ == null) {
          updates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          updatesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return port_ops.serialized_update.PortUpdatesProto.internal_static_PortUpdates_descriptor;
      }

      public port_ops.serialized_update.PortUpdatesProto.PortUpdates getDefaultInstanceForType() {
        return port_ops.serialized_update.PortUpdatesProto.PortUpdates.getDefaultInstance();
      }

      public port_ops.serialized_update.PortUpdatesProto.PortUpdates build() {
        port_ops.serialized_update.PortUpdatesProto.PortUpdates result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public port_ops.serialized_update.PortUpdatesProto.PortUpdates buildPartial() {
        port_ops.serialized_update.PortUpdatesProto.PortUpdates result = new port_ops.serialized_update.PortUpdatesProto.PortUpdates(this);
        int from_bitField0_ = bitField0_;
        if (updatesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            updates_ = java.util.Collections.unmodifiableList(updates_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.updates_ = updates_;
        } else {
          result.updates_ = updatesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof port_ops.serialized_update.PortUpdatesProto.PortUpdates) {
          return mergeFrom((port_ops.serialized_update.PortUpdatesProto.PortUpdates)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(port_ops.serialized_update.PortUpdatesProto.PortUpdates other) {
        if (other == port_ops.serialized_update.PortUpdatesProto.PortUpdates.getDefaultInstance()) return this;
        if (updatesBuilder_ == null) {
          if (!other.updates_.isEmpty()) {
            if (updates_.isEmpty()) {
              updates_ = other.updates_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUpdatesIsMutable();
              updates_.addAll(other.updates_);
            }
            onChanged();
          }
        } else {
          if (!other.updates_.isEmpty()) {
            if (updatesBuilder_.isEmpty()) {
              updatesBuilder_.dispose();
              updatesBuilder_ = null;
              updates_ = other.updates_;
              bitField0_ = (bitField0_ & ~0x00000001);
              updatesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUpdatesFieldBuilder() : null;
            } else {
              updatesBuilder_.addAllMessages(other.updates_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getUpdatesCount(); i++) {
          if (!getUpdates(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        port_ops.serialized_update.PortUpdatesProto.PortUpdates parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (port_ops.serialized_update.PortUpdatesProto.PortUpdates) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .SinglePortUpdate updates = 1;
      private java.util.List<port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate> updates_ =
        java.util.Collections.emptyList();
      private void ensureUpdatesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          updates_ = new java.util.ArrayList<port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate>(updates_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate, port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.Builder, port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdateOrBuilder> updatesBuilder_;

      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public java.util.List<port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate> getUpdatesList() {
        if (updatesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(updates_);
        } else {
          return updatesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public int getUpdatesCount() {
        if (updatesBuilder_ == null) {
          return updates_.size();
        } else {
          return updatesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate getUpdates(int index) {
        if (updatesBuilder_ == null) {
          return updates_.get(index);
        } else {
          return updatesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public Builder setUpdates(
          int index, port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate value) {
        if (updatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdatesIsMutable();
          updates_.set(index, value);
          onChanged();
        } else {
          updatesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public Builder setUpdates(
          int index, port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.Builder builderForValue) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.set(index, builderForValue.build());
          onChanged();
        } else {
          updatesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public Builder addUpdates(port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate value) {
        if (updatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdatesIsMutable();
          updates_.add(value);
          onChanged();
        } else {
          updatesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public Builder addUpdates(
          int index, port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate value) {
        if (updatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdatesIsMutable();
          updates_.add(index, value);
          onChanged();
        } else {
          updatesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public Builder addUpdates(
          port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.Builder builderForValue) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.add(builderForValue.build());
          onChanged();
        } else {
          updatesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public Builder addUpdates(
          int index, port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.Builder builderForValue) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.add(index, builderForValue.build());
          onChanged();
        } else {
          updatesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public Builder addAllUpdates(
          java.lang.Iterable<? extends port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate> values) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          super.addAll(values, updates_);
          onChanged();
        } else {
          updatesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public Builder clearUpdates() {
        if (updatesBuilder_ == null) {
          updates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          updatesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public Builder removeUpdates(int index) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.remove(index);
          onChanged();
        } else {
          updatesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.Builder getUpdatesBuilder(
          int index) {
        return getUpdatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdateOrBuilder getUpdatesOrBuilder(
          int index) {
        if (updatesBuilder_ == null) {
          return updates_.get(index);  } else {
          return updatesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public java.util.List<? extends port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdateOrBuilder> 
           getUpdatesOrBuilderList() {
        if (updatesBuilder_ != null) {
          return updatesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(updates_);
        }
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.Builder addUpdatesBuilder() {
        return getUpdatesFieldBuilder().addBuilder(
            port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.getDefaultInstance());
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.Builder addUpdatesBuilder(
          int index) {
        return getUpdatesFieldBuilder().addBuilder(
            index, port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.getDefaultInstance());
      }
      /**
       * <code>repeated .SinglePortUpdate updates = 1;</code>
       */
      public java.util.List<port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.Builder> 
           getUpdatesBuilderList() {
        return getUpdatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate, port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.Builder, port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdateOrBuilder> 
          getUpdatesFieldBuilder() {
        if (updatesBuilder_ == null) {
          updatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate, port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.Builder, port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdateOrBuilder>(
                  updates_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          updates_ = null;
        }
        return updatesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:PortUpdates)
    }

    static {
      defaultInstance = new PortUpdates(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PortUpdates)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PortUpdates_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PortUpdates_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021portUpdates.proto\032\026singlePortUpdate.pr" +
      "oto\"1\n\013PortUpdates\022\"\n\007updates\030\001 \003(\0132\021.Si" +
      "nglePortUpdateB.\n\032port_ops.serialized_up" +
      "dateB\020PortUpdatesProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PortUpdates_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PortUpdates_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PortUpdates_descriptor,
              new java.lang.String[] { "Updates", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          port_ops.serialized_update.SinglePortUpdateProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
