// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: singlePortUpdate.proto

package port_ops.serialized_update;

public final class SinglePortUpdateProto {
  private SinglePortUpdateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SinglePortUpdateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string local_switch_id = 1;
    /**
     * <code>required string local_switch_id = 1;</code>
     */
    boolean hasLocalSwitchId();
    /**
     * <code>required string local_switch_id = 1;</code>
     */
    java.lang.String getLocalSwitchId();
    /**
     * <code>required string local_switch_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getLocalSwitchIdBytes();

    // required int32 local_port_number = 2;
    /**
     * <code>required int32 local_port_number = 2;</code>
     */
    boolean hasLocalPortNumber();
    /**
     * <code>required int32 local_port_number = 2;</code>
     */
    int getLocalPortNumber();

    // required string remote_switch_id = 3;
    /**
     * <code>required string remote_switch_id = 3;</code>
     */
    boolean hasRemoteSwitchId();
    /**
     * <code>required string remote_switch_id = 3;</code>
     */
    java.lang.String getRemoteSwitchId();
    /**
     * <code>required string remote_switch_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getRemoteSwitchIdBytes();

    // required int32 remote_port_number = 4;
    /**
     * <code>required int32 remote_port_number = 4;</code>
     */
    boolean hasRemotePortNumber();
    /**
     * <code>required int32 remote_port_number = 4;</code>
     */
    int getRemotePortNumber();

    // required bool port_up = 5;
    /**
     * <code>required bool port_up = 5;</code>
     */
    boolean hasPortUp();
    /**
     * <code>required bool port_up = 5;</code>
     */
    boolean getPortUp();

    // required bool other_end_available = 6;
    /**
     * <code>required bool other_end_available = 6;</code>
     */
    boolean hasOtherEndAvailable();
    /**
     * <code>required bool other_end_available = 6;</code>
     */
    boolean getOtherEndAvailable();
  }
  /**
   * Protobuf type {@code SinglePortUpdate}
   */
  public static final class SinglePortUpdate extends
      com.google.protobuf.GeneratedMessage
      implements SinglePortUpdateOrBuilder {
    // Use SinglePortUpdate.newBuilder() to construct.
    private SinglePortUpdate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SinglePortUpdate(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SinglePortUpdate defaultInstance;
    public static SinglePortUpdate getDefaultInstance() {
      return defaultInstance;
    }

    public SinglePortUpdate getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SinglePortUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              localSwitchId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              localPortNumber_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              remoteSwitchId_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              remotePortNumber_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              portUp_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              otherEndAvailable_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return port_ops.serialized_update.SinglePortUpdateProto.internal_static_SinglePortUpdate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return port_ops.serialized_update.SinglePortUpdateProto.internal_static_SinglePortUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.class, port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.Builder.class);
    }

    public static com.google.protobuf.Parser<SinglePortUpdate> PARSER =
        new com.google.protobuf.AbstractParser<SinglePortUpdate>() {
      public SinglePortUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SinglePortUpdate(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SinglePortUpdate> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string local_switch_id = 1;
    public static final int LOCAL_SWITCH_ID_FIELD_NUMBER = 1;
    private java.lang.Object localSwitchId_;
    /**
     * <code>required string local_switch_id = 1;</code>
     */
    public boolean hasLocalSwitchId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string local_switch_id = 1;</code>
     */
    public java.lang.String getLocalSwitchId() {
      java.lang.Object ref = localSwitchId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localSwitchId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string local_switch_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLocalSwitchIdBytes() {
      java.lang.Object ref = localSwitchId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localSwitchId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 local_port_number = 2;
    public static final int LOCAL_PORT_NUMBER_FIELD_NUMBER = 2;
    private int localPortNumber_;
    /**
     * <code>required int32 local_port_number = 2;</code>
     */
    public boolean hasLocalPortNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 local_port_number = 2;</code>
     */
    public int getLocalPortNumber() {
      return localPortNumber_;
    }

    // required string remote_switch_id = 3;
    public static final int REMOTE_SWITCH_ID_FIELD_NUMBER = 3;
    private java.lang.Object remoteSwitchId_;
    /**
     * <code>required string remote_switch_id = 3;</code>
     */
    public boolean hasRemoteSwitchId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string remote_switch_id = 3;</code>
     */
    public java.lang.String getRemoteSwitchId() {
      java.lang.Object ref = remoteSwitchId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          remoteSwitchId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string remote_switch_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRemoteSwitchIdBytes() {
      java.lang.Object ref = remoteSwitchId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remoteSwitchId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 remote_port_number = 4;
    public static final int REMOTE_PORT_NUMBER_FIELD_NUMBER = 4;
    private int remotePortNumber_;
    /**
     * <code>required int32 remote_port_number = 4;</code>
     */
    public boolean hasRemotePortNumber() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 remote_port_number = 4;</code>
     */
    public int getRemotePortNumber() {
      return remotePortNumber_;
    }

    // required bool port_up = 5;
    public static final int PORT_UP_FIELD_NUMBER = 5;
    private boolean portUp_;
    /**
     * <code>required bool port_up = 5;</code>
     */
    public boolean hasPortUp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool port_up = 5;</code>
     */
    public boolean getPortUp() {
      return portUp_;
    }

    // required bool other_end_available = 6;
    public static final int OTHER_END_AVAILABLE_FIELD_NUMBER = 6;
    private boolean otherEndAvailable_;
    /**
     * <code>required bool other_end_available = 6;</code>
     */
    public boolean hasOtherEndAvailable() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bool other_end_available = 6;</code>
     */
    public boolean getOtherEndAvailable() {
      return otherEndAvailable_;
    }

    private void initFields() {
      localSwitchId_ = "";
      localPortNumber_ = 0;
      remoteSwitchId_ = "";
      remotePortNumber_ = 0;
      portUp_ = false;
      otherEndAvailable_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLocalSwitchId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocalPortNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRemoteSwitchId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRemotePortNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPortUp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOtherEndAvailable()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLocalSwitchIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, localPortNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRemoteSwitchIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, remotePortNumber_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, portUp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, otherEndAvailable_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLocalSwitchIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, localPortNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRemoteSwitchIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, remotePortNumber_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, portUp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, otherEndAvailable_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SinglePortUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return port_ops.serialized_update.SinglePortUpdateProto.internal_static_SinglePortUpdate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return port_ops.serialized_update.SinglePortUpdateProto.internal_static_SinglePortUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.class, port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.Builder.class);
      }

      // Construct using port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        localSwitchId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        localPortNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        remoteSwitchId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        remotePortNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        portUp_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        otherEndAvailable_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return port_ops.serialized_update.SinglePortUpdateProto.internal_static_SinglePortUpdate_descriptor;
      }

      public port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate getDefaultInstanceForType() {
        return port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.getDefaultInstance();
      }

      public port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate build() {
        port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate buildPartial() {
        port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate result = new port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.localSwitchId_ = localSwitchId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.localPortNumber_ = localPortNumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.remoteSwitchId_ = remoteSwitchId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.remotePortNumber_ = remotePortNumber_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.portUp_ = portUp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.otherEndAvailable_ = otherEndAvailable_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate) {
          return mergeFrom((port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate other) {
        if (other == port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate.getDefaultInstance()) return this;
        if (other.hasLocalSwitchId()) {
          bitField0_ |= 0x00000001;
          localSwitchId_ = other.localSwitchId_;
          onChanged();
        }
        if (other.hasLocalPortNumber()) {
          setLocalPortNumber(other.getLocalPortNumber());
        }
        if (other.hasRemoteSwitchId()) {
          bitField0_ |= 0x00000004;
          remoteSwitchId_ = other.remoteSwitchId_;
          onChanged();
        }
        if (other.hasRemotePortNumber()) {
          setRemotePortNumber(other.getRemotePortNumber());
        }
        if (other.hasPortUp()) {
          setPortUp(other.getPortUp());
        }
        if (other.hasOtherEndAvailable()) {
          setOtherEndAvailable(other.getOtherEndAvailable());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLocalSwitchId()) {
          
          return false;
        }
        if (!hasLocalPortNumber()) {
          
          return false;
        }
        if (!hasRemoteSwitchId()) {
          
          return false;
        }
        if (!hasRemotePortNumber()) {
          
          return false;
        }
        if (!hasPortUp()) {
          
          return false;
        }
        if (!hasOtherEndAvailable()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (port_ops.serialized_update.SinglePortUpdateProto.SinglePortUpdate) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string local_switch_id = 1;
      private java.lang.Object localSwitchId_ = "";
      /**
       * <code>required string local_switch_id = 1;</code>
       */
      public boolean hasLocalSwitchId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string local_switch_id = 1;</code>
       */
      public java.lang.String getLocalSwitchId() {
        java.lang.Object ref = localSwitchId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          localSwitchId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string local_switch_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLocalSwitchIdBytes() {
        java.lang.Object ref = localSwitchId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localSwitchId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string local_switch_id = 1;</code>
       */
      public Builder setLocalSwitchId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        localSwitchId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string local_switch_id = 1;</code>
       */
      public Builder clearLocalSwitchId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        localSwitchId_ = getDefaultInstance().getLocalSwitchId();
        onChanged();
        return this;
      }
      /**
       * <code>required string local_switch_id = 1;</code>
       */
      public Builder setLocalSwitchIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        localSwitchId_ = value;
        onChanged();
        return this;
      }

      // required int32 local_port_number = 2;
      private int localPortNumber_ ;
      /**
       * <code>required int32 local_port_number = 2;</code>
       */
      public boolean hasLocalPortNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 local_port_number = 2;</code>
       */
      public int getLocalPortNumber() {
        return localPortNumber_;
      }
      /**
       * <code>required int32 local_port_number = 2;</code>
       */
      public Builder setLocalPortNumber(int value) {
        bitField0_ |= 0x00000002;
        localPortNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 local_port_number = 2;</code>
       */
      public Builder clearLocalPortNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        localPortNumber_ = 0;
        onChanged();
        return this;
      }

      // required string remote_switch_id = 3;
      private java.lang.Object remoteSwitchId_ = "";
      /**
       * <code>required string remote_switch_id = 3;</code>
       */
      public boolean hasRemoteSwitchId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string remote_switch_id = 3;</code>
       */
      public java.lang.String getRemoteSwitchId() {
        java.lang.Object ref = remoteSwitchId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          remoteSwitchId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string remote_switch_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRemoteSwitchIdBytes() {
        java.lang.Object ref = remoteSwitchId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remoteSwitchId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string remote_switch_id = 3;</code>
       */
      public Builder setRemoteSwitchId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        remoteSwitchId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string remote_switch_id = 3;</code>
       */
      public Builder clearRemoteSwitchId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        remoteSwitchId_ = getDefaultInstance().getRemoteSwitchId();
        onChanged();
        return this;
      }
      /**
       * <code>required string remote_switch_id = 3;</code>
       */
      public Builder setRemoteSwitchIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        remoteSwitchId_ = value;
        onChanged();
        return this;
      }

      // required int32 remote_port_number = 4;
      private int remotePortNumber_ ;
      /**
       * <code>required int32 remote_port_number = 4;</code>
       */
      public boolean hasRemotePortNumber() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 remote_port_number = 4;</code>
       */
      public int getRemotePortNumber() {
        return remotePortNumber_;
      }
      /**
       * <code>required int32 remote_port_number = 4;</code>
       */
      public Builder setRemotePortNumber(int value) {
        bitField0_ |= 0x00000008;
        remotePortNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 remote_port_number = 4;</code>
       */
      public Builder clearRemotePortNumber() {
        bitField0_ = (bitField0_ & ~0x00000008);
        remotePortNumber_ = 0;
        onChanged();
        return this;
      }

      // required bool port_up = 5;
      private boolean portUp_ ;
      /**
       * <code>required bool port_up = 5;</code>
       */
      public boolean hasPortUp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bool port_up = 5;</code>
       */
      public boolean getPortUp() {
        return portUp_;
      }
      /**
       * <code>required bool port_up = 5;</code>
       */
      public Builder setPortUp(boolean value) {
        bitField0_ |= 0x00000010;
        portUp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool port_up = 5;</code>
       */
      public Builder clearPortUp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        portUp_ = false;
        onChanged();
        return this;
      }

      // required bool other_end_available = 6;
      private boolean otherEndAvailable_ ;
      /**
       * <code>required bool other_end_available = 6;</code>
       */
      public boolean hasOtherEndAvailable() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bool other_end_available = 6;</code>
       */
      public boolean getOtherEndAvailable() {
        return otherEndAvailable_;
      }
      /**
       * <code>required bool other_end_available = 6;</code>
       */
      public Builder setOtherEndAvailable(boolean value) {
        bitField0_ |= 0x00000020;
        otherEndAvailable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool other_end_available = 6;</code>
       */
      public Builder clearOtherEndAvailable() {
        bitField0_ = (bitField0_ & ~0x00000020);
        otherEndAvailable_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SinglePortUpdate)
    }

    static {
      defaultInstance = new SinglePortUpdate(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SinglePortUpdate)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SinglePortUpdate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SinglePortUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026singlePortUpdate.proto\"\252\001\n\020SinglePortU" +
      "pdate\022\027\n\017local_switch_id\030\001 \002(\t\022\031\n\021local_" +
      "port_number\030\002 \002(\005\022\030\n\020remote_switch_id\030\003 " +
      "\002(\t\022\032\n\022remote_port_number\030\004 \002(\005\022\017\n\007port_" +
      "up\030\005 \002(\010\022\033\n\023other_end_available\030\006 \002(\010B3\n" +
      "\032port_ops.serialized_updateB\025SinglePortU" +
      "pdateProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SinglePortUpdate_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SinglePortUpdate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SinglePortUpdate_descriptor,
              new java.lang.String[] { "LocalSwitchId", "LocalPortNumber", "RemoteSwitchId", "RemotePortNumber", "PortUp", "OtherEndAvailable", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
