// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ftableUpdates.proto

package ft_ops.serialized_update;

public final class FTableUpdatesProto {
  private FTableUpdatesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FTableUpdatesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .SingleFTableUpdate updates = 1;
    /**
     * <code>repeated .SingleFTableUpdate updates = 1;</code>
     */
    java.util.List<ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate> 
        getUpdatesList();
    /**
     * <code>repeated .SingleFTableUpdate updates = 1;</code>
     */
    ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate getUpdates(int index);
    /**
     * <code>repeated .SingleFTableUpdate updates = 1;</code>
     */
    int getUpdatesCount();
    /**
     * <code>repeated .SingleFTableUpdate updates = 1;</code>
     */
    java.util.List<? extends ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdateOrBuilder> 
        getUpdatesOrBuilderList();
    /**
     * <code>repeated .SingleFTableUpdate updates = 1;</code>
     */
    ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdateOrBuilder getUpdatesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code FTableUpdates}
   */
  public static final class FTableUpdates extends
      com.google.protobuf.GeneratedMessage
      implements FTableUpdatesOrBuilder {
    // Use FTableUpdates.newBuilder() to construct.
    private FTableUpdates(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FTableUpdates(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FTableUpdates defaultInstance;
    public static FTableUpdates getDefaultInstance() {
      return defaultInstance;
    }

    public FTableUpdates getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FTableUpdates(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                updates_ = new java.util.ArrayList<ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate>();
                mutable_bitField0_ |= 0x00000001;
              }
              updates_.add(input.readMessage(ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          updates_ = java.util.Collections.unmodifiableList(updates_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ft_ops.serialized_update.FTableUpdatesProto.internal_static_FTableUpdates_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ft_ops.serialized_update.FTableUpdatesProto.internal_static_FTableUpdates_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates.class, ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates.Builder.class);
    }

    public static com.google.protobuf.Parser<FTableUpdates> PARSER =
        new com.google.protobuf.AbstractParser<FTableUpdates>() {
      public FTableUpdates parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FTableUpdates(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FTableUpdates> getParserForType() {
      return PARSER;
    }

    // repeated .SingleFTableUpdate updates = 1;
    public static final int UPDATES_FIELD_NUMBER = 1;
    private java.util.List<ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate> updates_;
    /**
     * <code>repeated .SingleFTableUpdate updates = 1;</code>
     */
    public java.util.List<ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate> getUpdatesList() {
      return updates_;
    }
    /**
     * <code>repeated .SingleFTableUpdate updates = 1;</code>
     */
    public java.util.List<? extends ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdateOrBuilder> 
        getUpdatesOrBuilderList() {
      return updates_;
    }
    /**
     * <code>repeated .SingleFTableUpdate updates = 1;</code>
     */
    public int getUpdatesCount() {
      return updates_.size();
    }
    /**
     * <code>repeated .SingleFTableUpdate updates = 1;</code>
     */
    public ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate getUpdates(int index) {
      return updates_.get(index);
    }
    /**
     * <code>repeated .SingleFTableUpdate updates = 1;</code>
     */
    public ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdateOrBuilder getUpdatesOrBuilder(
        int index) {
      return updates_.get(index);
    }

    private void initFields() {
      updates_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getUpdatesCount(); i++) {
        if (!getUpdates(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < updates_.size(); i++) {
        output.writeMessage(1, updates_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < updates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, updates_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FTableUpdates}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ft_ops.serialized_update.FTableUpdatesProto.FTableUpdatesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ft_ops.serialized_update.FTableUpdatesProto.internal_static_FTableUpdates_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ft_ops.serialized_update.FTableUpdatesProto.internal_static_FTableUpdates_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates.class, ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates.Builder.class);
      }

      // Construct using ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUpdatesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (updatesBuilder_ == null) {
          updates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          updatesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ft_ops.serialized_update.FTableUpdatesProto.internal_static_FTableUpdates_descriptor;
      }

      public ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates getDefaultInstanceForType() {
        return ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates.getDefaultInstance();
      }

      public ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates build() {
        ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates buildPartial() {
        ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates result = new ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates(this);
        int from_bitField0_ = bitField0_;
        if (updatesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            updates_ = java.util.Collections.unmodifiableList(updates_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.updates_ = updates_;
        } else {
          result.updates_ = updatesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates) {
          return mergeFrom((ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates other) {
        if (other == ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates.getDefaultInstance()) return this;
        if (updatesBuilder_ == null) {
          if (!other.updates_.isEmpty()) {
            if (updates_.isEmpty()) {
              updates_ = other.updates_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUpdatesIsMutable();
              updates_.addAll(other.updates_);
            }
            onChanged();
          }
        } else {
          if (!other.updates_.isEmpty()) {
            if (updatesBuilder_.isEmpty()) {
              updatesBuilder_.dispose();
              updatesBuilder_ = null;
              updates_ = other.updates_;
              bitField0_ = (bitField0_ & ~0x00000001);
              updatesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUpdatesFieldBuilder() : null;
            } else {
              updatesBuilder_.addAllMessages(other.updates_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getUpdatesCount(); i++) {
          if (!getUpdates(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ft_ops.serialized_update.FTableUpdatesProto.FTableUpdates) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .SingleFTableUpdate updates = 1;
      private java.util.List<ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate> updates_ =
        java.util.Collections.emptyList();
      private void ensureUpdatesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          updates_ = new java.util.ArrayList<ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate>(updates_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate, ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate.Builder, ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdateOrBuilder> updatesBuilder_;

      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public java.util.List<ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate> getUpdatesList() {
        if (updatesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(updates_);
        } else {
          return updatesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public int getUpdatesCount() {
        if (updatesBuilder_ == null) {
          return updates_.size();
        } else {
          return updatesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate getUpdates(int index) {
        if (updatesBuilder_ == null) {
          return updates_.get(index);
        } else {
          return updatesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public Builder setUpdates(
          int index, ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate value) {
        if (updatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdatesIsMutable();
          updates_.set(index, value);
          onChanged();
        } else {
          updatesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public Builder setUpdates(
          int index, ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate.Builder builderForValue) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.set(index, builderForValue.build());
          onChanged();
        } else {
          updatesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public Builder addUpdates(ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate value) {
        if (updatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdatesIsMutable();
          updates_.add(value);
          onChanged();
        } else {
          updatesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public Builder addUpdates(
          int index, ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate value) {
        if (updatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdatesIsMutable();
          updates_.add(index, value);
          onChanged();
        } else {
          updatesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public Builder addUpdates(
          ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate.Builder builderForValue) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.add(builderForValue.build());
          onChanged();
        } else {
          updatesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public Builder addUpdates(
          int index, ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate.Builder builderForValue) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.add(index, builderForValue.build());
          onChanged();
        } else {
          updatesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public Builder addAllUpdates(
          java.lang.Iterable<? extends ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate> values) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          super.addAll(values, updates_);
          onChanged();
        } else {
          updatesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public Builder clearUpdates() {
        if (updatesBuilder_ == null) {
          updates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          updatesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public Builder removeUpdates(int index) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.remove(index);
          onChanged();
        } else {
          updatesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate.Builder getUpdatesBuilder(
          int index) {
        return getUpdatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdateOrBuilder getUpdatesOrBuilder(
          int index) {
        if (updatesBuilder_ == null) {
          return updates_.get(index);  } else {
          return updatesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public java.util.List<? extends ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdateOrBuilder> 
           getUpdatesOrBuilderList() {
        if (updatesBuilder_ != null) {
          return updatesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(updates_);
        }
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate.Builder addUpdatesBuilder() {
        return getUpdatesFieldBuilder().addBuilder(
            ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate.getDefaultInstance());
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate.Builder addUpdatesBuilder(
          int index) {
        return getUpdatesFieldBuilder().addBuilder(
            index, ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate.getDefaultInstance());
      }
      /**
       * <code>repeated .SingleFTableUpdate updates = 1;</code>
       */
      public java.util.List<ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate.Builder> 
           getUpdatesBuilderList() {
        return getUpdatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate, ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate.Builder, ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdateOrBuilder> 
          getUpdatesFieldBuilder() {
        if (updatesBuilder_ == null) {
          updatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate, ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdate.Builder, ft_ops.serialized_update.SingleFTableUpdateProto.SingleFTableUpdateOrBuilder>(
                  updates_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          updates_ = null;
        }
        return updatesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:FTableUpdates)
    }

    static {
      defaultInstance = new FTableUpdates(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FTableUpdates)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FTableUpdates_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FTableUpdates_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ftableUpdates.proto\032\030singleFTableUpdat" +
      "e.proto\"5\n\rFTableUpdates\022$\n\007updates\030\001 \003(" +
      "\0132\023.SingleFTableUpdateB.\n\030ft_ops.seriali" +
      "zed_updateB\022FTableUpdatesProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_FTableUpdates_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_FTableUpdates_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FTableUpdates_descriptor,
              new java.lang.String[] { "Updates", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ft_ops.serialized_update.SingleFTableUpdateProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
